# Generated by Django 6.0.1 on 2026-01-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_semanal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
