# Generated by Django 6.0.1 on 2026-01-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_locacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
