# Generated by Django 6.0.2 on 2026-02-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0004_alter_locacao_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
